### PR TITLE
Add View Helper to read an item's enclosure data

### PR DESCRIPTION
**Pull request by maryisdead**
I just needed that today and from what I can see this isn't possible with the tools the extension provides right now. Any obligations?

### CODE REVIEW

**Comment by maryisdead** [comment]
Ah, man … new to this pull request stuff. Didn't know that it'd merge my second commit into this PR.

**Comment by fabarea** [comment]
Can I ask what TYPO3 version 6 vs 7 you have used? The flexform handling is slightly different between these two versions.

**Comment by maryisdead** [comment]
This was tested against a 6.2.12.

**Comment by artus70** [comment]
@maryisdead The second commit throughs a php exception in TYPO3 7.6.6 that the $string parameter inside xml2array is aleady an array.

**Comment by maryisdead** [comment]
I see … bummer. I'll take some time this weekend and see which version introduced the change and will then wrap that in a condition. Thanks for the heads-up!

**Comment by Mabahe** [comment]
Jep, call xml2array only if value is no array to have it compatible with v6 and v7, see https://github.com/Mabahe/rss_display/commit/4d8f024f6c19389b8ae725e8fd649f485ffd1044

**Pull request closed without merging**
